### PR TITLE
optimized bit select using BMI2's pdep

### PR DESCRIPTION
**Pull request by tetzank**
BMI2's pdep instruction can be used to make bit selection much faster
than the current approach.

It uses pdep in a different way than normally, setting the data as mask
and using a word as source operand which has only the i-th bit set.
As a result we get the i-th bit in data isolated. By counting the
trailing zeros (tzcnt) we get the position which is the result of
select.

### CODE REVIEW

**Comment by mpetri** [comment]
This is strange. I thought I committed this change a while ago? Must have been the v3 repo.

**Comment by mpetri** [comment]
This probably needs some modifications to cmake to detect bmi2 and add the -mbmi2 flag if it is available

**Comment by tetzank** [comment]
What about just using -march=native by default? If one wants to deactivate some things, he can still do so  by changing it with ccmake for example. I don't see the point in adding compile-time detection to the build system. Let the compiler do it.

What is the v3 repo? Is it public?

**Comment by mpetri** [comment]
The sdsl-lite v3 repo can be found here: https://github.com/xxsds/sdsl-lite but is in a very unstable state and the sdsl-lite core team is busy with other things currently so the effort to get v3 out has stalled currently.

Can you change the CMakefile to add "-march=native". I would then merge this patch.

**Comment by tetzank** [comment]
I added -march=native.

One could now also remove the SSE check and do some other cleanup in the CMakeLists.txt. Not sure if that's worth it if you are already working on sdsl v3 which has a revamped build system anyways.

**Comment by mpetri** [comment]
Thanks for the contribution.

**Pull request merged**
